#!/usr/bin/env bash
hex_with_alpha() {
    # Return normalized 8-digit hex (RRGGBBAA) without '#' and in lowercase.
    # Accepts #RRGGBB / RRGGBB / #RGB / RGB and alpha as hex (ff) or float (0..1).
    local hex="${1#\#}"
    local alpha="${2:-ff}"

    # Expand 3-digit hex to 6-digit
    if [[ ${#hex} -eq 3 ]]; then
        hex="${hex:0:1}${hex:0:1}${hex:1:1}${hex:1:1}${hex:2:1}${hex:2:1}"
    fi

    # Validate hex length
    if [[ ${#hex} -ne 6 ]]; then
        echo "000000ff"
        return 1
    fi

    # Normalize alpha:
    if [[ "$alpha" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
        # float 0..1 -> two-digit hex
        alpha=$(awk -v a="$alpha" 'BEGIN{ if(a<0) a=0; if(a>1) a=1; printf "%02x", int(a*255+0.5)}')
    else
        # hex form: normalize single digit and ensure two digits
        alpha="${alpha#\#}"
        if [[ ${#alpha} -eq 1 ]]; then
            alpha="${alpha}${alpha}"
        fi
        if [[ ${#alpha} -ne 2 ]]; then
            alpha="ff"
        fi
        # lower-case
        alpha="${alpha,,}"
    fi

    # return lowercase hex + alpha
    echo "${hex,,}${alpha}"
}

NAME="$1"
OUT="$HOME/.config/themes/current.css"
OUT_CONF="$HOME/.config/themes/current.conf"
OUT_RASI="$HOME/.config/themes/current.rasi"
WAL="$HOME/.cache/wal/colors"
WAL_IMG="$HOME/.cache/wal/wal"

readarray -t COLORS < "$WAL"
if [ -f "$WAL_IMG" ]; then
    WALLPAPER=$(cat "$WAL_IMG")
else
    WALLPAPER="$HOME/Bilder/wallpapers/default.jpg" # Fallback
fi

# Here you can generate different theme files using the colors from pywal

cat > "$OUT_CONF" <<- EOF
# Theme configuration generated by wallpaperengine for: $NAME
\$wallpaper = $WALLPAPER
\$bg = rgba($(hex_with_alpha "${COLORS[0]}" d9))
\$fg = rgba($(hex_with_alpha "${COLORS[7]}" ff))
\$accent = rgba($(hex_with_alpha "${COLORS[3]}" ff))

\$color0 = rgba($(hex_with_alpha "${COLORS[0]}" ff))
\$color1 = rgba($(hex_with_alpha "${COLORS[1]}" ff))
\$color2 = rgba($(hex_with_alpha "${COLORS[2]}" ff))
\$color3 = rgba($(hex_with_alpha "${COLORS[3]}" ff))
\$color4 = rgba($(hex_with_alpha "${COLORS[4]}" ff))
\$color5 = rgba($(hex_with_alpha "${COLORS[5]}" ff))
\$color6 = rgba($(hex_with_alpha "${COLORS[6]}" ff))
\$color7 = rgba($(hex_with_alpha "${COLORS[7]}" ff))
\$color8 = rgba($(hex_with_alpha "${COLORS[8]}" ff))
\$color9 = rgba($(hex_with_alpha "${COLORS[9]}" ff))
\$color10 = rgba($(hex_with_alpha "${COLORS[10]}" ff))
\$color11 = rgba($(hex_with_alpha "${COLORS[11]}" ff))
\$color12 = rgba($(hex_with_alpha "${COLORS[12]}" ff))
\$color13 = rgba($(hex_with_alpha "${COLORS[13]}" ff))
\$color14 = rgba($(hex_with_alpha "${COLORS[14]}" ff))
\$color15 = rgba($(hex_with_alpha "${COLORS[15]}" ff))
EOF

# A waybar theme using the generated colors
cat > "$OUT" <<- EOF
/* Generated Waybar theme for: $NAME */
@define-color bg ${COLORS[0]};
@define-color fg ${COLORS[7]};
@define-color accent ${COLORS[3]};

@define-color color0 ${COLORS[0]};
@define-color color1 ${COLORS[1]};
@define-color color2 ${COLORS[2]};
@define-color color3 ${COLORS[3]};
@define-color color4 ${COLORS[4]};
@define-color color5 ${COLORS[5]};
@define-color color6 ${COLORS[6]};
@define-color color7 ${COLORS[7]};
@define-color color8 ${COLORS[8]};
@define-color color9 ${COLORS[9]};
@define-color color10 ${COLORS[10]};
@define-color color11 ${COLORS[11]};
@define-color color12 ${COLORS[12]};
@define-color color13 ${COLORS[13]};
@define-color color14 ${COLORS[14]};
@define-color color15 ${COLORS[15]};
EOF

# Generate Kitty theme
KITTY_CONF="$HOME/.config/kitty/colors-matugen.conf"
cat > "$KITTY_CONF" <<- EOF
# Generated by generate_theme.sh
background ${COLORS[0]}
foreground ${COLORS[7]}
cursor ${COLORS[7]}
selection_background ${COLORS[7]}
selection_foreground ${COLORS[0]}

color0 ${COLORS[0]}
color1 ${COLORS[1]}
color2 ${COLORS[2]}
color3 ${COLORS[3]}
color4 ${COLORS[4]}
color5 ${COLORS[5]}
color6 ${COLORS[6]}
color7 ${COLORS[7]}
color8 ${COLORS[8]}
color9 ${COLORS[9]}
color10 ${COLORS[10]}
color11 ${COLORS[11]}
color12 ${COLORS[12]}
color13 ${COLORS[13]}
color14 ${COLORS[14]}
color15 ${COLORS[15]}
EOF

# Generate Oh My Posh theme
OMP_TEMPLATE="$HOME/.config/ohmyposh/mytheme.omp.json.template"
OMP_OUT="$HOME/.config/ohmyposh/mytheme.omp.json"

if [ -f "$OMP_TEMPLATE" ]; then
    cp "$OMP_TEMPLATE" "$OMP_OUT"
    for i in {15..0}; do
        sed -i "s/COLOR_$i/${COLORS[$i]}/g" "$OMP_OUT"
    done
    echo "Oh My Posh theme generated at $OMP_OUT"
    # Reload Oh My Posh prompt in all open fish terminals
    fish -c 'oh-my-posh init fish --config $HOME/.config/ohmyposh/mytheme.omp.json | source'
else
    echo "Oh My Posh template not found at $OMP_TEMPLATE"
fi
