general {
    lock_cmd = pidof hyprlock || hyprlock --immediate
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Step 1: Dim screen after 2 minutes
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10% && hyprctl dispatch dpms off
    on-resume = brightnessctl -r && hyprctl dispatch dpms on
}

# Step 2: Lock screen after 2.5 minutes
listener {
    timeout = 150
    on-timeout = loginctl lock-session
}

# Steg 3: Suspend 
listener {
     timeout = 600
     on-timeout = systemctl suspend
}
