package theme

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"quickshell/internal/colors"
	"quickshell/internal/files"
)

type Outputs struct {
	ConfPath string
	CSSPath  string
	GTKPath  string
}

func WriteAll(p files.Paths, palette colors.Palette, wallpaper string) (Outputs, error) {
	name := strings.TrimSuffix(filepath.Base(wallpaper), filepath.Ext(wallpaper))

	if err := writeCurrentConf(p.ThemeConf, name, wallpaper, palette); err != nil {
		return Outputs{}, err
	}
	if err := ensureQuickshellThemeLink(p); err != nil {
		return Outputs{}, err
	}
	if err := writeCurrentCSS(p.ThemeCSS, name, palette); err != nil {
		return Outputs{}, err
	}
	if err := writeKittyTheme(p.KittyTheme, palette); err != nil {
		return Outputs{}, err
	}
	if err := writeOhMyPoshPalette(p.OhMyPoshTheme, palette); err != nil {
		return Outputs{}, err
	}
	if err := writeGtkTheme(p.ThemeGTK, palette); err != nil {
		return Outputs{}, err
	}
	if err := ensureGtkLinks(p); err != nil {
		return Outputs{}, err
	}
	if err := writeHyprWallpaperLua(p.HyprWallpaperLua, wallpaper); err != nil {
		return Outputs{}, err
	}
	return Outputs{ConfPath: p.ThemeConf, CSSPath: p.ThemeCSS, GTKPath: p.ThemeGTK}, nil
}

func writeCurrentConf(path, name, wallpaper string, pal colors.Palette) error {
	toRGBA := func(hex, alpha string) string {
		return fmt.Sprintf("rgba(%s%s)", colors.HexNoHash(hex), strings.ToLower(alpha))
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Theme configuration generated by quickshell-shell for: %s\n", name)
	fmt.Fprintf(&b, "$wallpaper = %s\n", wallpaper)
	fmt.Fprintf(&b, "$bg = %s\n", toRGBA(pal.BG, "d9"))
	fmt.Fprintf(&b, "$fg = %s\n", toRGBA(pal.FG, "ff"))
	fmt.Fprintf(&b, "$accent = %s\n\n", toRGBA(pal.Accent, "ff"))
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&b, "$color%d = %s\n", i, toRGBA(pal.Colors[i], "ff"))
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeCurrentCSS(path, name string, pal colors.Palette) error {
	var b strings.Builder
	fmt.Fprintf(&b, "/* Generated Waybar theme for: %s */\n", name)
	fmt.Fprintf(&b, "@define-color bg %s;\n", pal.BG)
	fmt.Fprintf(&b, "@define-color fg %s;\n", pal.FG)
	fmt.Fprintf(&b, "@define-color accent %s;\n\n", pal.Accent)
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&b, "@define-color color%d %s;\n", i, pal.Colors[i])
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeKittyTheme(path string, pal colors.Palette) error {
	var b strings.Builder
	b.WriteString("# Generated by wpctl\n")
	fmt.Fprintf(&b, "background %s\n", pal.Colors[0])
	fmt.Fprintf(&b, "foreground %s\n", pal.Colors[7])
	fmt.Fprintf(&b, "cursor %s\n", pal.Colors[7])
	fmt.Fprintf(&b, "selection_background %s\n", pal.Colors[7])
	fmt.Fprintf(&b, "selection_foreground %s\n\n", pal.Colors[0])
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&b, "color%d %s\n", i, pal.Colors[i])
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeGtkTheme(path string, pal colors.Palette) error {
	var b strings.Builder
	b.WriteString("@define-color accent_color " + pal.Colors[1] + ";\n")
	b.WriteString("@define-color accent_bg_color " + pal.Colors[1] + ";\n")
	b.WriteString("@define-color accent_fg_color " + pal.Colors[0] + ";\n\n")
	b.WriteString("@define-color window_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color window_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color view_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color view_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color headerbar_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color headerbar_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color headerbar_border_color " + pal.Colors[1] + ";\n")
	b.WriteString("@define-color card_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color card_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color popover_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color popover_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color dialog_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color dialog_fg_color " + pal.Colors[7] + ";\n\n")
	b.WriteString("@define-color theme_fg_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color theme_bg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color theme_text_color " + pal.Colors[7] + ";\n")
	b.WriteString("@define-color theme_base_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color theme_selected_bg_color " + pal.Colors[1] + ";\n")
	b.WriteString("@define-color theme_selected_fg_color " + pal.Colors[0] + ";\n")
	b.WriteString("@define-color borders " + pal.Colors[1] + ";\n")
	b.WriteString("@define-color unfocused_borders " + pal.Colors[8] + ";\n")
	b.WriteString("\n/* Keep Nautilus sidebar aligned with theme colors. */\n")
	b.WriteString("placessidebar, .navigation-sidebar, .sidebar {\n")
	b.WriteString("  background-color: alpha(@window_bg_color, 0.96);\n")
	b.WriteString("  color: @window_fg_color;\n")
	b.WriteString("}\n")
	b.WriteString("placessidebar row, .navigation-sidebar row {\n")
	b.WriteString("  background-color: transparent;\n")
	b.WriteString("  color: @window_fg_color;\n")
	b.WriteString("  border-radius: 8px;\n")
	b.WriteString("}\n")
	b.WriteString("placessidebar row:hover, .navigation-sidebar row:hover {\n")
	b.WriteString("  background-color: alpha(@accent_bg_color, 0.18);\n")
	b.WriteString("}\n")
	b.WriteString("placessidebar row:selected, .navigation-sidebar row:selected {\n")
	b.WriteString("  background-color: alpha(@accent_bg_color, 0.30);\n")
	b.WriteString("  color: @accent_fg_color;\n")
	b.WriteString("}\n")
	b.WriteString("\n/* Force Nautilus/libadwaita headerbar and top-left area to themed colors. */\n")
	b.WriteString("headerbar, .titlebar, .nautilus-window headerbar, .nautilus-window .titlebar {\n")
	b.WriteString("  background-color: @headerbar_bg_color;\n")
	b.WriteString("  color: @headerbar_fg_color;\n")
	b.WriteString("}\n")
	b.WriteString("headerbar:backdrop, .titlebar:backdrop, .nautilus-window headerbar:backdrop {\n")
	b.WriteString("  background-color: shade(@headerbar_bg_color, 0.95);\n")
	b.WriteString("  color: @headerbar_fg_color;\n")
	b.WriteString("}\n")
	b.WriteString("headerbar separator, .titlebar separator, .nautilus-window headerbar separator {\n")
	b.WriteString("  background-color: @headerbar_border_color;\n")
	b.WriteString("}\n")
	b.WriteString(".nautilus-window toolbarview, .nautilus-window toolbarview > box, .nautilus-window .sidebar-pane, .nautilus-window .sidebar-pane toolbar {\n")
	b.WriteString("  background-color: @headerbar_bg_color;\n")
	b.WriteString("  color: @headerbar_fg_color;\n")
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeOhMyPoshPalette(path string, pal colors.Palette) error {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat oh-my-posh theme: %w", err)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read oh-my-posh theme: %w", err)
	}

	var root map[string]any
	if err := json.Unmarshal(raw, &root); err != nil {
		return fmt.Errorf("parse oh-my-posh theme json: %w", err)
	}

	paletteAny, hasPalette := root["palette"]
	paletteMap, ok := paletteAny.(map[string]any)
	if !hasPalette || !ok {
		paletteMap = map[string]any{}
	}

	paletteMap["bg"] = pal.BG
	paletteMap["fg"] = pal.FG
	paletteMap["accent"] = pal.Accent
	for i := 0; i < 16; i++ {
		paletteMap[fmt.Sprintf("color%d", i)] = pal.Colors[i]
	}
	root["palette"] = paletteMap

	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal oh-my-posh theme json: %w", err)
	}
	out = append(out, '\n')
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return fmt.Errorf("write oh-my-posh theme: %w", err)
	}
	return nil
}

func ensureQuickshellThemeLink(p files.Paths) error {
	_ = os.Remove(p.QuickshellThemeConf)
	if err := os.Symlink(p.ThemeConf, p.QuickshellThemeConf); err == nil {
		return nil
	}

	// Fallback to copying if symlinks are unavailable.
	b, err := os.ReadFile(p.ThemeConf)
	if err != nil {
		return fmt.Errorf("read canonical theme conf: %w", err)
	}
	if err := os.WriteFile(p.QuickshellThemeConf, b, 0o644); err != nil {
		return fmt.Errorf("write quickshell theme conf copy: %w", err)
	}
	return nil
}

func ensureGtkLinks(p files.Paths) error {
	gtk3css := filepath.Join(p.Gtk3Dir, "gtk.css")
	gtk3dark := filepath.Join(p.Gtk3Dir, "gtk-dark.css")
	gtk4css := filepath.Join(p.Gtk4Dir, "gtk.css")
	gtk4dark := filepath.Join(p.Gtk4Dir, "gtk-dark.css")

	for _, f := range []string{gtk3css, gtk3dark, gtk4css, gtk4dark} {
		_ = os.Remove(f)
		if err := os.Symlink(p.ThemeGTK, f); err != nil {
			return fmt.Errorf("link %s -> %s: %w", f, p.ThemeGTK, err)
		}
	}
	return nil
}

func writeHyprWallpaperLua(path, wallpaper string) error {
	content := fmt.Sprintf("hl.on(\"hyprland.start\", function()\n    hl.exec_cmd(\"awww-daemon &\")\n    hl.exec_cmd(\"awww img \\\"%s\\\" --transition-type grow\")\nend)\n", wallpaper)
	return os.WriteFile(path, []byte(content), 0o644)
}
